import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const distRoot = path.join(projectRoot, 'dist')
const builtHtml = await readFile(path.join(distRoot, 'index.html'), 'utf8')

function builtAsset(pattern, label) {
  const matches = [...builtHtml.matchAll(pattern)]
  if (matches.length !== 1) throw new Error(`Expected one ${label} in dist/index.html; found ${matches.length}.`)
  const relative = matches[0][1].match(/(?:^|\/)(assets\/[A-Za-z0-9._-]+)$/)?.[1]
  if (!relative) throw new Error(`Unexpected ${label} path: ${matches[0][1]}`)
  return path.join(distRoot, relative)
}

const scriptPath = builtAsset(/<script\b[^>]*\btype="module"[^>]*\bsrc="([^"]+)"[^>]*><\/script>/g, 'JavaScript entry')
const stylePath = builtAsset(/<link\b[^>]*\brel="stylesheet"[^>]*\bhref="([^"]+)"[^>]*>/g, 'stylesheet')
const [script, style, favicon, sampleCsv] = await Promise.all([
  readFile(scriptPath, 'utf8'),
  readFile(stylePath, 'utf8'),
  readFile(path.join(projectRoot, 'public', 'favicon.svg')),
  readFile(path.join(projectRoot, 'public', 'sample-ar-aging.csv')),
])

// Keep this as one file. If Vite starts emitting extra assets, fail instead of
// quietly producing a broken offline release.
if (/<\/script/i.test(script) || /<\/style/i.test(style)) throw new Error('An asset contains an unsafe HTML closing tag.')
if (/\b(?:url\(|@import\b)/i.test(style)) throw new Error('The stylesheet has an external asset reference.')

const faviconUrl = `data:image/svg+xml;base64,${favicon.toString('base64')}`
const sampleCsvUrl = `data:text/csv;charset=utf-8;base64,${sampleCsv.toString('base64')}`
const offlineHtml = `<!doctype html>
<!-- Generated by npm run build. Edit the source app and scripts/build-offline.mjs instead. -->
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="theme-color" content="#102e34" />
    <meta name="description" content="Turn an aging report into an action plan. Track invoice blockers, owners, payment promises, and the next move in a private workspace." />
    <link rel="icon" type="image/svg+xml" href="${faviconUrl}" />
    <title>Duenara — Turn overdue invoices into clear next moves</title>
    <style>${style}</style>
    <script>window.__DUENARA_SAMPLE_CSV_URL__ = ${JSON.stringify(sampleCsvUrl)};</script>
  </head>
  <body>
    <div id="root"></div>
    <script type="module">${script}</script>
  </body>
</html>
`

await Promise.all([
  writeFile(path.join(projectRoot, 'Duenara-offline.html'), offlineHtml),
  writeFile(path.join(distRoot, 'Duenara-offline.html'), offlineHtml),
  // Retain the legacy filename for people who already saved the offline app.
  writeFile(path.join(projectRoot, 'PromiseLedger-offline.html'), offlineHtml),
  writeFile(path.join(distRoot, 'PromiseLedger-offline.html'), offlineHtml),
])
console.log(`Wrote self-contained Duenara-offline.html (${Buffer.byteLength(offlineHtml).toLocaleString()} bytes).`)
